### ISSUE TITLE
How to make this display on a public web page?

### ISSUE THREAD

**Issue by NostrNews** [metasikander/s0str#5]
I think I can get this running on a VPS just fine, but I want the output, my nostr feed, to be the content of a web page.

So when the public browses mydomain.com they'll see a purple page with a s0str feed of my Nostr posts.

Is there a way to create an index.html file on the VPS server and post this feed in the middle of that page? What snippet can I put in that page to make it display?

Thanks in advance.

**Comment by metasikander** [comment]
yes it should be possible with a html based client.
a client is just some software that connects to the relay, so it should be possible to set up a html page that connects to the relay and reads all the notes that are stored there.
unfortunatelly i don't know of any projects that does that, but maybe take a look [here](https://github.com/aljazceru/awesome-nostr). maybe there are something you can use here.
